### PR TITLE
it's `require 'capistrano/delayed-jobs'`

### PR DESCRIPTION
**Pull request by fauno**
the readme says capistrano3 :)

### CODE REVIEW

**Comment by mauriciopasquier** [comment]
That's for [another gem](/capistrano-plugins/capistrano-delayed-job#setup-and-usage) @fauno

**Comment by goooseman** [comment]
True, that's not for this gem

**Comment by fauno** [comment]
From a project already in production:

### Gemfile

``` ruby
gem 'delayed_job_active_record'
group :development do
  gem 'capistrano-rails'
  gem 'capistrano3-delayed-job'
end
```

### Capfile

``` ruby
require 'capistrano/rails'
require 'capistrano/delayed-job'
```

The other gem says `require 'capistrano/delayed_job'`, notice the underscore @mauriciopasquier @goooseman

**Comment by fauno** [comment]
`LoadError: cannot load such file -- capistrano3/delayed-job` :)

**Comment by goooseman** [comment]
Ok,  you win ;)

**Pull request merged**
